env:
  global:
    - DOCKER_USER: rhololkeolke
    - secure: d4lw/g9bVPdAmGvxXFhQ+r5ukpFdPHEiqgJCwth6Cx/fa6FKweA521G3lYtAHRKc7B2FcR5xx1J1KxTJKliZTFd5u2Z3V+xpVsqLA1szUE2BFH1xysR2Gd7Mi0QWbPnW1rcqVsX5eRCijP+PqKGRsdRwflkBP4XDTt8Jg6vEmyJSx/hHRotZi5PqiGU/bAwm9dw4TNQijEedmQ1M68+U4t8mpOSaTPgqXepcDVJhrrioSnyojtuRd5k3qH1eIW5udfjFjT09XLi3272Gz4pQ1xha/s2AuBjeXe9Q+1EqXcApUevOz154eCOQVFM+MNU0Fg+TmqScXP+P/pobth43qo4LFpUThfIzKmAs5dWSmmDrdqK4XsXUbcUzZK1DBiHb5tF68qI3oREMUVd45kjA8dz1SF5tZzd/7FxJDmybFTB3bpWnPwk/KFumshLMZpbzT8xbUu2t148GOpUeXzIU6FV6It8pbG0frsZZcrXrpxFU4EdlAmIt9qquQJfOjTNwaGpQXqe5BGQVeMtYAyzsVts4uCx+XgcGnc+6ceirl+ZA4V2kO1iMwLpOSvM3tHc6e0Khsjy3sxpokKEfrojeFp+omlGFWqUZ6M41go9udrj34FXqn16EXRchCs4+hA9sqJHvhhvk57AyB5PltH8KeLswkliKUewpocw9MHTXtRY=
sudo: required
services:
- docker
before_install:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
install:
  - docker pull redcoolbeans/dockerlint
stages:
  - conan-images
  - dart-model-explorer
jobs:
  include:
    - stage: conan-images
      before_script:
        - docker run -it --rm -v "$(pwd)/clang8/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
      script:
        - export TAG_CLANG8=rhololkeolke/clang8:$TRAVIS_COMMIT
        - docker build ./clang8 -t $TAG_CLANG8
      after_success:
        - docker tag $TAG_CLANG8 rhololkeolke/clang8:$TRAVIS_COMMIT
        - test $TRAVIS_BRANCH = "master" && docker push rhololkeolke/clang8
    - stage: conan-images
      before_script:
        - docker run -it --rm -v "$(pwd)/clang7/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
      script:
        - export TAG_CLANG7=rhololkeolke/clang7:$TRAVIS_COMMIT
        - docker build ./clang7 -t $TAG_CLANG7
      after_success:
        - docker tag $TAG_CLANG7 rhololkeolke/clang7:$TRAVIS_COMMIT
        - test $TRAVIS_BRANCH = "master" && docker push rhololkeolke/clang7
    - stage: conan-images
      before_script:
        - docker run -it --rm -v "$(pwd)/gcc8/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
      script:
        - export TAG_GCC8=rhololkeolke/gcc8:$TRAVIS_COMMIT
        - docker build ./gcc8 -t $TAG_GCC8
      after_success:
        - docker tag $TAG_GCC8 rhololkeolke/gcc8:$TRAVIS_COMMIT
        - test $TRAVIS_BRANCH = "master" && docker push rhololkeolke/gcc8
    - stage: conan-images
      before_script:
        - docker run -it --rm -v "$(pwd)/gcc9/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
      script:
        - export TAG_GCC9=rhololkeolke/gcc9:$TRAVIS_COMMIT
        - docker build ./gcc9 -t $TAG_GCC9
      after_success:
        - docker tag $TAG_GCC9 rhololkeolke/gcc9:$TRAVIS_COMMIT
        - test $TRAVIS_BRANCH = "master" && docker push rhololkeolke/gcc9

    - stage: dart-model-explorer
      before_script:
        - docker run -it --rm -v "$(pwd)/dart-model-explorer/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
      script:
        - export TAG_DART_MODEL_EXPLORER=rhololkeolke/dart-model-explorer:$TRAVIS_COMMIT
        - docker build ./dart-model-explorer -t $TAG_DART_MODEL_EXPLORER
      after_success:
        - docker tag $TAG_DART_MODEL_EXPLORER rhololkeolke/dart-model-explorer:latest
        - test $TRAVIS_BRANCH = "master" && docker push rhololkeolke/dart-model-explorer
